### ISSUE TITLE
加个判断 if(this.showBg){   }

### ISSUE THREAD

**Issue by william-xue** [AD-feiben/blog-admin#1]
![image](https://user-images.githubusercontent.com/20151622/38989864-c7df6bc8-440a-11e8-913e-0a4d74de2d9c.png)

![image](https://user-images.githubusercontent.com/20151622/38989890-e0a15356-440a-11e8-9f61-a2a5c88f7ddc.png)

**Comment by AD-feiben** [comment]
thank you very much
